name: 'AzureResources'
 
on:
  workflow_dispatch:

jobs:
  dev:
    name: 'dev'
    environment: dev
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SKIP_PROVIDER_REGISTRATION: true
      
      TERM: linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./zones/trusted
 
    steps:
    - uses: hashicorp/setup-terraform@v2
