name: 'Main'
 
on:
  workflow_dispatch:
    inputs:
      delete:
        description: "Select yes if you want to delete the resources."
        type: choice
        required: true
        options:
        - no
        - yes

jobs:
  dev:
    name: 'dev'
    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{secrets.CONFLUENT_CLOUD_API_SECRET}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      run: |
        if ${{ github.event.inputs.delete }} == 'yes'
          terraform plan -delete -auto-approve
        then
          terraform plan -auto-approve
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: |
        if ${{ github.event.inputs.delete }} == 'yes'
          terraform apply -delete -auto-approve
        then
          terraform apply -auto-approve
