name: 'SemiTrustedZone-Topics'
 
on:
  workflow_dispatch:

jobs:
  dev:
    name: 'dev'
    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{secrets.CONFLUENT_CLOUD_API_SECRET}}
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./onboarding/semitrusted
 
    steps:
    - uses: hashicorp/setup-terraform@v2
    
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan -var "app_manager_api_key=${{ secrets.SEMITRUSTED_API_MANAGER_KEY }}" -var "app_manager_api_secret=${{ secrets.SEMITRUSTED_API_MANAGER_SECRET }}"
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -var "app_manager_api_key=${{ secrets.SEMITRUSTED_API_MANAGER_KEY }}" -var "app_manager_api_secret=${{ secrets.SEMITRUSTED_API_MANAGER_SECRET }}" -auto-approve
