name: 'TrustedZone'
 
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read 

jobs:
  dev:
    name: 'dev'
    environment: dev
    env:
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{secrets.CONFLUENT_CLOUD_API_SECRET}}
      
      ARM_USE_MSI: true
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      
      TERM: linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
 
    steps:
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}            

    - uses: hashicorp/setup-terraform@v2

    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      working-directory: ./zones/trusted
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      working-directory: ./zones/trusted
      run: terraform init
 
    - name: 'Terraform Validate'
      id: validate
      working-directory: ./zones/trusted
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      working-directory: ./zones/trusted
      run: terraform plan
 
    - name: Terraform Apply
      id: apply
      working-directory: ./zones/trusted
      if: github.ref == 'refs/heads/main'
      run: terraform apply --auto-approve
