name: 'TrustedZone'
 
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  dev:
    name: 'dev'
    env:
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
      CONFLUENT_CLOUD_API_KEY: ${{ secrets.CONFLUENT_CLOUD_API_KEY }}
      CONFLUENT_CLOUD_API_SECRET: ${{secrets.CONFLUENT_CLOUD_API_SECRET}}
      
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      
      TERM: linux
    runs-on: ubuntu-latest
    environment: dev
 
    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./zones/trusted
 
    steps:
    - uses: hashicorp/setup-terraform@v2

    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
    
    - name: 'Checkout'
      id: checkout
      uses: actions/checkout@v3
 
    - name: 'Terraform Format'
      id: format
      run: terraform fmt
         
    - name: 'Terraform Init'
      id: init
      run: terraform init
 
    - name: 'Terraform Validate'
      id: validate
      run: terraform validate

    - name: 'Terraform Plan'
      id: plan
      run: terraform plan
 
    - name: Terraform Apply
      id: apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply --auto-approve
